### ISSUE TITLE
Open Hardware?

### ISSUE THREAD

**Issue by duven87** [jorcuad/FreePhone#1]
Hola chicos! para empezar enhorabuena por ese curro que os habeis metido creando un telefono con piezas arduino. Tiene muy buena pinta y ojala el proyecto crezca en un futuro.

Solo tengo una pregunta.. he oido que los firmwares de todos los wifis y gsm no son libres.

Mi pregunta seria saber si me equivoco y si vuestro telefono es 100% con hardware libre?
He estado leyendo articulos como Librem y Fairphone y aunque no esten mal del hardware cerrado no se libra ninguno.

Gracias

Un saludo y mucho animo!

**Comment by jorcuad** [comment]
Siento decirte que no, al menos hasta donde yo sé, no hay chipsets que implementen el protocolo GSM (u otros protocolos más recientes como 3G/4G) que puedan adquirirse de forma comercial y sean hardware libre. El módulo GSM que se usa en el proyecto si que es hardware libre excepto por el chipset que monta, un SIMCOM 900.

La forma de conexión entre la RPI y el módulo GSM es mediante serial, por lo que, en caso de que en un futuro apareciese un chipset abierto, si se puede conectar mediante serial, todo lo que recoge la wiki sobre como montar el teléfono seguiría siendo válido para ese módulo.

¡Gracias por tu interés!
¡Un saludo!
